#!/bin/sh

#result=`ps aux | grep -i "node" | grep -v "grep" | wc -l`
result=`ps | grep -i "node" | grep -v "grep" | wc -l`

case "$1" in
"start")
if [ $result -ge 1 ]
   then
        echo "already started, nothing to do!"
   else
        cd /home/node/comundo_webservice 
        node . > webservice.log 2> webservice-err.log &
	echo "started now"
fi
;;
"stop")
if [ $result -ge 1 ]
   then
        /usr/bin/pkill node
	echo "stopped" 
   else
        echo "already stopped"
fi
;;
"restart")
if [ $result -ge 1 ]
   then
        /usr/bin/pkill node
        cd /home/node/comundo_webservice 
        node . > webservice.log 2> webservice-err.log & 
	echo "stopped and restarted"
   else 
        cd /home/node/comundo_webservice 
        node . > webservice.log 2> webservice-err.log & 
	echo "wasn't running, started now!"
fi
;;
"status")
if [ $result -ge 1 ]
   then
        echo "running"
   else
        echo "NOT running"
fi
;;
*)
if [ $result -ge 1 ]
   then
        echo "already started, nothing to do!"
   else
        cd /home/node/comundo_webservice
        node . > webservice.log 2> webservice-err.log & 
        echo "started now"
fi
;;
esac
